RegisterComponent<EditorController>("Editor Controller", true);
RegisterComponent<EntityPickingComponent>("Entity Picking", true);
RegisterComponent<Sprite>("Sprite");
RegisterComponent<Collider>("Collider");
RegisterComponent<Transform>("Transform");
RegisterComponent<PlayerController>("Player Controller");
RegisterComponent<CameraComponent>("Camera");
RegisterComponent<Rigidbody>("Rigidbody");
RegisterComponent<MaterialComponent>("Material"); 
RegisterComponent<MeshRendererComponent>("Mesh Renderer");