#pragma once

enum class eMessage
{
	eStartGame,
	eQuitGame,
	eOpenSettings,
	ePopStack,
	ePopStackToMainMenu,
	eStartLevel1,
	eStartLevel2,
	eStartLevel3,
	eStartLevel4,
	eStartLevel5,
	ePauseGame,
	eOpenLevelSelect,
	eChangeMasterVolume,
	eChangeMusicVolume,
	eChangeSFXVolume,
	eGeneralLevelUp,
	ePlayerDied,
	eRespawn,
	eUpdateResolution,
	eOpenCredits,
	ePlayerDetected,
	ePlayerDisappeared,
	eEnemyAlerted,
	eEnemyAlertRemove,

	eTutorial_Combat,
	eTutorial_Story1,
	eTutorial_Story2,
	eTutorial_Story3,

	eCullBack,
	eCullNone,
	eCullFront,

	e960x540 = 540,
	e1280x720 = 720,
	e1600x900 = 900,
	e1920x1080 = 1080,
	e2560x1440 = 1440,

	eUI_Menu_ChangeTo_MainMenu,
	eUI_Menu_ChangeTo_Credits,
	eUI_Menu_Push_PauseMenu,
	eUI_Element_Button_Back,
	eUI_Element_Button_Play,
	eUI_Element_Button_Options,
	eUI_Element_Button_Credits,
	eUI_Element_Button_LevelSelect,
	eUI_Element_Button_Level_1,
	eUI_Element_Button_Level_2,
	eUI_Element_Button_Level_3,
	eUI_Element_Button_Exit,
	eGame_Event_Changed_To_Level_1,
	eGame_Event_Changed_To_Level_2,
	eGame_Event_Changed_To_Level_3,
	eGame_Event_PauseGame,
	eGame_Event_ResumeGame,
	eGame_Event_LevelLoaded,
};